### ISSUE TITLE
Firefox crash with installed plugin

### ISSUE THREAD

**Issue by AnKekk** [open-eid/firefox-pkcs11-loader#30] opened 2020-08-03 11:32 UTC
Firefox crashes without any notification:
OS Windows 10 64bit version 2004 (OS build 19041.388)
Firefox 79.0 64bit

Faulting application name: firefox.exe, version: 79.0.0.7506, time stamp: 0x5f1601d7
Faulting module name: onepin-opensc-pkcs11.dll, version: 0.20.1.920, time stamp: 0x5eb3c069
Exception code: 0xc0000409
Fault offset: 0x000000000028ea3c
Faulting process id: 0x2e8c
Faulting application start time: 0x01d66988830b2ed7
Faulting application path: C:\Program Files\Mozilla Firefox\firefox.exe
Faulting module path: C:\Windows\System32\onepin-opensc-pkcs11.dll
Report Id: a4f3a8d1-3305-4b2a-96ed-e94102e9c52c
Faulting package full name: 
Faulting package-relative application ID: 

Fault bucket 1651066186720628429, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: firefox.exe
P2: 79.0.0.7506
P3: 5f1601d7
P4: onepin-opensc-pkcs11.dll
P5: 0.20.1.920
P6: 5eb3c069
P7: 000000000028ea3c
P8: c0000409
P9: 0000000000000005
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5E42.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5F6B.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5F7C.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5F8A.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5F9A.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_firefox.exe_f2cd3ca5ad95f87bfc79142da694c8f8161057f3_c03c6358_22e73a37-76a4-4477-b08d-8bc25e8a7df3

Analysis symbol: 
Rechecking for solution: 0
Report Id: a4f3a8d1-3305-4b2a-96ed-e94102e9c52c
Report Status: 268435456
Hashed bucket: a6730c7a2947726d56e9c3f2f8244ecd
Cab Guid: 0

**Comment by ridgewell** [comment] 2020-08-05 00:58
I am confirming that I am experiencing the same issue. The most recent update caused my Firefox installation to randomly crash without generating a crash report. It is sudden, hangs up, and just quits.

The issue does not occur when Safe mode is enabled. The issue continues to occur in normal mode, even with all extensions disabled (including the eID extensions), hardware acceleration disabled and within the default theme. 

Disabling the two eID extensions including PKCS11-Loader did not resolve the issue. The only way I was able to resolve this was by uninstalling the eID software entirely.

**Comment by ridgewell** [comment] 2020-08-05 01:01
I am confirming that I am experiencing the same issue. The most recent update caused my Firefox installation to randomly crash without generating a crash report. It is sudden, hangs up, and just quits. It is very frequent (approximately after ~15-20 min of uptime). Unfortunately I'm unable to provide a report from about:crashes in Firefox as a result.

I experience this just by browsing normally (not using any functionalities of the eID extension/application, or Digidoc).

The issue does not occur when Safe mode is enabled. The issue continues to occur in normal mode, even with all extensions disabled (including the eID extensions), hardware acceleration disabled and within the default theme. 

I have gone through the troubleshooting steps found at https://support.mozilla.org/en-US/kb/firefox-crashes-troubleshoot-prevent-and-get-help, including checking for RAM errors using Windows memory test and updating my ATI Radeon graphics drivers.

Disabling the two eID extensions including PKCS11-Loader did not resolve the issue. The only way I was able to resolve this was by uninstalling the eID software entirely.

**Comment by metsma** [comment] 2020-08-05 04:39
https://github.com/OpenSC/OpenSC/issues/1999

**Comment by martinpaljak** [comment] 2020-08-05 04:54
If the issue is fixed upstream, why is there no hotfix available?

**Comment by metsma** [comment] 2020-11-20 06:20
This is resolved in latest release.

**Closed as completed by metsma** 2020-11-20 06:20 UTC
